// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCADCsg9YWLyhL8ZkwR3cGaxcf6b1w7WS8',
    appId: '1:1069779906581:web:845c09597cd89032495e1c',
    messagingSenderId: '1069779906581',
    projectId: 'ditonton-a976e',
    authDomain: 'ditonton-a976e.firebaseapp.com',
    storageBucket: 'ditonton-a976e.appspot.com',
    measurementId: 'G-QS6W3VVPHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSfJx_U1exEbYPZeI2dpuYvNooti_MbWM',
    appId: '1:1069779906581:android:cb2d2039e5e1f40a495e1c',
    messagingSenderId: '1069779906581',
    projectId: 'ditonton-a976e',
    storageBucket: 'ditonton-a976e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAsGiBjBDswq41Lr69e-dBS_4xjteQghs',
    appId: '1:1069779906581:ios:9c160e6f44e4606e495e1c',
    messagingSenderId: '1069779906581',
    projectId: 'ditonton-a976e',
    storageBucket: 'ditonton-a976e.appspot.com',
    iosClientId:
        '1069779906581-rfak5vpntvb3l1hl0c321rbtg0kd5e3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ditonton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAsGiBjBDswq41Lr69e-dBS_4xjteQghs',
    appId: '1:1069779906581:ios:9c160e6f44e4606e495e1c',
    messagingSenderId: '1069779906581',
    projectId: 'ditonton-a976e',
    storageBucket: 'ditonton-a976e.appspot.com',
    iosClientId:
        '1069779906581-rfak5vpntvb3l1hl0c321rbtg0kd5e3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ditonton',
  );
}
